#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Runs on pre-commit hook, only on staged files(TODO: use to standardize commit messages)
# npx lerna exec --concurrency 1 --stream lint-staged --since HEAD --exclude-dependents # Using lerna
npm exec --workspaces -- lint-staged --verbose --concurrent 1