#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Runs on pre-commit hook(before commit)

## check code lint, type check and unit tests(lint-staged runs individually per staged files packages)
# npm exec --workspaces -- lint-staged --verbose --concurrent 1     # old simpler script
npx --workspaces -c '\
    echo -n ${PWD##*/} \\t\\t\\t && \
    lint-staged --verbose --concurrent 1 \
'